# Generated by Django 4.2 on 2023-04-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
                ('feedback', models.TextField()),
                ('good_point', models.TextField()),
            ],
        ),
    ]
