# Generated by Django 4.2.1 on 2023-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                related_name="followers", to="accounts.profile"
            ),
        ),
    ]
